# Generated by Django 5.2 on 2025-04-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secret", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="secret",
            name="secret_key",
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name="Код доступа"),
        ),
        migrations.AlterField(
            model_name="secret",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Наименование секрета"),
        ),
        migrations.AlterField(
            model_name="secret",
            name="passphrase",
            field=models.TextField(
                blank=True, max_length=100, null=True, verbose_name="Пароль для дополнительной защиты"
            ),
        ),
    ]
