# Generated by Django 5.2 on 2025-04-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("secret", "0002_secret_secret_key_alter_secret_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="secret",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активность секрета"),
        ),
    ]
