version: "3.11.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_one_time_secrets
    ports:
      - 8000:8000
    volumes:
      - .:/code
      - static_volume:/code/static
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    container_name: db_one_time_secrets
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  celery:
    container_name: celery_one_time_secrets
    build: .
    environment:
      - REDIS_URL=redis://redis:6379/0
    command: sh -c "celery -A config.celery worker --loglevel=INFO -B"
    restart: on-failure
    depends_on:
      - db
      - redis
    env_file: "./.env"

  redis:
    container_name: redis_one_time_secrets
    image: redis:7.4
    restart: always
    ports:
      - "6380:6379"
    env_file: "./.env"
    volumes:
      - ./redis/data:/root/redis

  celery-beat:
    build: .
    container_name: celery_beat_one_time_secrets
    restart: always
    depends_on:
      - db
      - redis
    command: sh -c "celery -A config.celery  beat --loglevel=info"

volumes:
  postgres_data:
  static_volume:
